### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ugintl** [nikolajanko/Invoicepls.com#1]
1. How to upload my own template?

2. Is there an admin user?

**Comment by nikolajanko** [comment]
1. There is no option to upload your own template.
2. No for now, all user have same options. Maybe in future.

**Comment by ugintl** [comment]
@nikolajanko How to add my template using code?

**Comment by nikolajanko** [comment]
@ugintl It is a little bit complicated, I'm using FPDF for templates and you need to manualy adjust all the filds and to make your own design for template.

**Comment by ugintl** [comment]
@nikolajanko Atleast tell me what folder contains the template?
